FROM node:alpine as builder

ENV NODE_ENV=production

WORKDIR /app

COPY package*.json .

RUN npm ci 

COPY . .

RUN npm run build

FROM nginx:alpine

# Some frameworks use dist other use build if you are using a framework that uses build change this
COPY --from=builder /app/dist /var/www/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]