FROM node:alpine as builder

ENV NODE_ENV=production

WORKDIR /app

COPY package*.json .

RUN npm ci

COPY . .

RUN npm run build

FROM node:alpine

WORKDIR /app

COPY --from=builder /app/dist /app 

# If using another PORT change this
EXPOSE 3000

CMD [ "node", "index" ]