name: Deploy master to server
run-name: ${{ github.actor }} is deploying master to server
on:
    push:
        : main
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Pull and run on remote
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  script: |
                      cd ~/${{ env.PROJECT_NAME }}
                      git pull
                      echo ${{ secrets.PASSWORD}} | sudo -S docker compose build
                      echo ${{ secrets.PASSWORD}} | sudo -S docker compose up -d
